## springboot整合rabbitmq的基本配置
spring:
#  rabbitmq:
#    addresses: 127.0.0.1:5672
#    username: guest
#    password: guest
#    virtual-host: /
### 消费端配置
#    listener:
#      simple:
#        concurrency: 5
#        ## manual:手动 ack（确认）
#        acknowledge-mode: manual
#        max-concurrency: 10
#        prefetch: 1
  datasource:
      url: jdbc:mysql://localhost:3306/rabbitmq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 8002
  servlet:
    context-path: /

v2:
  spring:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      listener:
        simple:
          concurrency: 5
          ## manual:手动 ack（确认）
          acknowledge-mode: manual
          #消费者的最大数量
          max-concurrency: 10
          #在单个请求中处理的消息个数，他应该大于等于事务数量
          prefetch: 1
      #设置此属性配置可以确保消息成功发送到交换器
      publisher-confirms: true
      #可以确保消息在未被队列接收时返回
      publisher-returns: true
      template:
        mandatory: true
v1:
  spring:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      listener:
        simple:
          concurrency: 5
          ## manual:手动 ack（确认）
          acknowledge-mode: manual
          #消费者的最大数量
          max-concurrency: 10
          #在单个请求中处理的消息个数，他应该大于等于事务数量
          prefetch: 1
      #设置此属性配置可以确保消息成功发送到交换器
      publisher-confirms: true
      #可以确保消息在未被队列接收时返回
      publisher-returns: true
      template:
        mandatory: true